name: snps
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - bcftools=1.10.2
  - binutils_impl_linux-64=2.34
  - binutils_linux-64=2.34
  - biopython=1.79
  - bwidget=1.9.14
  - bz2file=0.98
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - curl=7.71.1
  - cycler=0.10.0
  - decorator=5.0.9
  - expat=2.2.9
  - fontconfig=2.13.1
  - freebayes=1.3.2
  - freetype=2.10.2
  - fribidi=1.0.10
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - glib=2.66.0
  - graphite2=1.3.13
  - graphviz=2.42.3
  - gsl=2.6
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - harfbuzz=2.7.2
  - htslib=1.10.2
  - icu=67.1
  - isa-l=2.30.0
  - jpeg=9d
  - kernel-headers_linux-64=2.6.32
  - khmer=3.0.0a3
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - kwip=0.2.0
  - lcms2=2.11
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libdeflate=1.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - make=4.3
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - ncurses=6.2
  - networkx=2.5
  - numpy=1.19.1
  - olefile=0.46
  - openssl=1.1.1k
  - pango=1.42.4
  - parallel=20200722
  - pcre=8.44
  - pcre2=10.35
  - perl=5.30.3
  - pigz=2.6
  - pillow=7.2.0
  - pip=20.2.3
  - pixman=0.38.0
  - pthread-stubs=0.4
  - pyfaidx=0.6.1
  - pyparsing=2.4.7
  - pysam=0.16.0.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-isal=0.10.0
  - python_abi=3.8
  - r-base=4.0.2
  - r-dotcall64=1.0_0
  - r-fields=11.4
  - r-maps=3.3.0
  - r-spam=2.5_1
  - readline=8.0
  - samtools=1.10
  - scipy=1.5.2
  - screed=1.0.4
  - sed=4.8
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - sysroot_linux-64=2.12
  - tk=8.6.10
  - tktable=2.10
  - tornado=6.0.4
  - whatshap=1.1
  - wheel=0.35.1
  - xopen=1.1.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
